# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e6a115b74b33daf1941a85eac36dbc7966935295905974e98cff49b1fd4f17228e57eb0e67f72313c6ca9d488bab8839e0adb8d29af0bfa477c0235487e0aa6

test:
  secret_key_base: 35b2117a269fd5dc947be9d2f2c21076e5fd7b0559a9daa1cc11f0cc8845a50e3badf6d6fd5c857d7e461b5f795685ed21ab66f4c7183379a9d2b9868dc92dd5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
